version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    platform: linux/amd64
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/usr/share/nginx/html/
